### ISSUE TITLE
The program quits after reading the first line of contact map

### ISSUE THREAD

**Issue by kai3192** [kundajelab/genomedisco#4]
Hi,

The example works fine for me but when I try to run whole genome files (in the format chr bin chr bin value) it gets stuck at the splitting step reads on the first line and quits.

Any suggestions ?
Thanks,
Kaivalya
Files are attached
[sorted_0hr_WT_1mb.txt.gz](https://github.com/kundajelab/genomedisco/files/4099243/sorted_0hr_WT_1mb.txt.gz)
[hg19_1MB_bins.bed.gz](https://github.com/kundajelab/genomedisco/files/4099244/hg19_1MB_bins.bed.gz)
[0hr_WT_edges_splitting_out.chr1.txt](https://github.com/kundajelab/genomedisco/files/4099251/0hr_WT_edges_splitting_out.chr1.txt)

**Comment by oursu-broad** [comment]
Hi @kai3192 

Thanks for the issue and for linking the files.

When testing your files, I think they had an unusual format (sometimes this type of format would appear for me when using files saved in Excel, because the characters that represent the end of each line in the file are different between the files saved in Excel and what Unix servers would expect. I'm not sure, though, whether this is the reason for your problem).

In any case, I was able to convert your files to a format that I could then run genomedisco on, successfully. 

The commands I used were:
```
gunzip hg19_1MB_bins.bed.gz
perl -pe 's/\r\n|\n|\r/\n/g' hg19_1MB_bins.bed > hg19_1MB_bins_fixed.bed
cat hg19_1MB_bins_fixed.bed | gzip > hg19_1MB_bins_fixed.bed.gz

gunzip sorted_0hr_WT_1mb.txt.gz
perl -pe 's/\r\n|\n|\r/\n/g' sorted_0hr_WT_1mb.txt > sorted_0hr_WT_1mb_fixed.txt
cat sorted_0hr_WT_1mb_fixed.txt | gzip > sorted_0hr_WT_1mb_fixed.txt.gz
```
Try it out and please let us know if you still have issues!

Best,
Oana

**Comment by kai3192** [comment]
I tried it out and I got a new error when I try to run the first step of preprocess
"
Traceback (most recent call last):
  File "/usr/local/bin/genomedisco", line 11, in <module>
    load_entry_point('genomedisco', 'console_scripts', 'genomedisco')()
  File "/Users/kaivalyashevade/genomedisco/genomedisco/__main__.py", line 17, in main
    command_methods[command](**args)
  File "/Users/kaivalyashevade/genomedisco/genomedisco/concordance_utils.py", line 152, in preprocess
    parameters=read_parameters_file(parameters_file)
  File "/Users/kaivalyashevade/genomedisco/genomedisco/concordance_utils.py", line 284, in read_parameters_file
    method_name,param_name,param_value=items[0],items[1],items[2]
IndexError: list index out of range "

**Comment by kai3192** [comment]
Here are the files that I used now

[hg19_1MB_bins_fixed.bed.gz](https://github.com/kundajelab/genomedisco/files/4114133/hg19_1MB_bins_fixed.bed.gz)
[sorted_0hr_WT_1mb_fixed.txt.gz](https://github.com/kundajelab/genomedisco/files/4114134/sorted_0hr_WT_1mb_fixed.txt.gz)
[sorted_fCHD7_0hr_1mb_fixed.txt.gz](https://github.com/kundajelab/genomedisco/files/4114135/sorted_fCHD7_0hr_1mb_fixed.txt.gz)

**Comment by kai3192** [comment]
I fixed it there was a error in my parameters file.

Thank you for your help ! Works perfectly now!
Kaivalya
